services:
  cassandra:
    image: cassandra:4.1.7
    container_name: cassandra
    hostname: cassandra
    restart: unless-stopped
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_NUM_TOKENS=4
      - HEAP_NEWSIZE=1280M
      - MAX_HEAP_SIZE=200M
    volumes:
      - ./cassandra/data:/var/lib/cassandra
      - ./cassandra/logs:/var/log/cassandra
    deploy:
      resources:
        limits:
          memory: 2G
    memswap_limit: 2G
    labels:
      com.strangebee.stack: "thehive-cortex-stack"
      com.strangebee.service: "cassandra"
      com.strangebee.role: "database"
      com.strangebee.environment: "testing"
      com.strangebee.dependency: "None"

  elasticsearch:
    image: elasticsearch:7.17.26
    container_name: elasticsearch
    hostname: elasticsearch
    restart: unless-stopped
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=100000
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2G
    memswap_limit: 2G
    labels:
      com.strangebee.stack: "thehive-cortex-stack"
      com.strangebee.service: "elasticsearch"
      com.strangebee.role: "indexing"
      com.strangebee.environment: "testing"
      com.strangebee.dependency: "None"

  thehive:
    image: strangebee/thehive:5.4.2-1
    container_name: thehive
    hostname: thehive
    restart: unless-stopped
    environment:
      - |
        JAVA_OPTS=
          -Xms1280M
          -Xmx1280M
          -XX:MaxMetaspaceSize=400m
          -XX:ReservedCodeCacheSize=250m
      - "--s3-endpoint"
      - "http://minio:9002"
      - "--s3-access-key"
      - "minioadmin"
      - "--s3-secret-key"
      - "minioadmin"
      - "--s3-use-path-access-style"
    volumes:
      - ./thehive/config:/etc/thehive:ro
      - ./thehive/data/files:/opt/thp/thehive/files
      - ./thehive/logs:/opt/thehive/logs
    ports:
      - '0.0.0.0:9000:9000'
    depends_on:
      - elasticsearch
      - cassandra
      - cortex
      - misp
    labels:
      com.strangebee.stack: "thehive-cortex-stack"
      com.strangebee.service: "thehive"
      com.strangebee.role: "application"
      com.strangebee.environment: "testing"
      com.strangebee.dependency: "elasticsearch, cassandra"

  cortex:
    image: thehiveproject/cortex:latest
    container_name: cortex
    hostname: cortex
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xms1000M -Xmx1000M -XX:MaxMetaspaceSize=400m -XX:ReservedCodeCacheSize=250m
      - es_uri=http://elasticsearch:9200
      - job_directory=/tmp/cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/cortex-jobs:/tmp/cortex-jobs
      - ./cortex/config:/etc/cortex:ro
      - ./cortex/logs:/var/log/cortex
      - /opt/cortex/analyzers/analyzers:/opt/cortex/analyzers
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    deploy:
      resources:
        limits:
          memory: 2G
    memswap_limit: 2G
    ports:
      - '9001:9001'
    depends_on:
      - elasticsearch
    labels:
      com.strangebee.stack: "thehive-cortex-stack"
      com.strangebee.service: "cortex"
      com.strangebee.role: "application"
      com.strangebee.environment: "testing"
      com.strangebee.dependency: "elasticsearch"

  misp:
    container_name: misp
    image: coolacid/misp-docker:core-latest
    depends_on:
      - misp_mysql
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - "./misp/server-configs/:/var/www/MISP/app/Config/"
      - "./misp/logs/:/var/www/MISP/app/tmp/logs/"
      - "./misp/files/:/var/www/MISP/app/files"
      - "./misp/ssl/:/etc/nginx/certs"
    environment:
      - MYSQL_HOST=misp_mysql
      - MYSQL_DATABASE=mispdb
      - MYSQL_USER=mispuser
      - MYSQL_PASSWORD=misppass
      - MISP_ADMIN_EMAIL=mispadmin@fcup.pt
      - MISP_ADMIN_PASSPHRASE=adminpass
      - MISP_BASEURL=localhost
      - TIMEZONE=Europe/London
      - INIT=true
      - CRON_USER_ID=1
      - REDIS_FQDN=redis

  misp_mysql:
    image: mysql:8.0.40-debian
    restart: unless-stopped
    volumes:
      - ./mispsqldata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mispdb
      - MYSQL_USER=mispuser
      - MYSQL_PASSWORD=misppass
      - MYSQL_ROOT_PASSWORD=mispass

  misp-modules:
    image: coolacid/misp-docker:modules-latest
    environment:
      - "REDIS_BACKEND=redis"
    depends_on:
      - redis
      - misp_mysql

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "9003:8001"
    volumes:
      - ./redis:/data

  minio:
    image: minio/minio:latest
    command: [ "minio", "server", "/data", "--console-address", ":9002" ]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9002:9002"
      - "9005:9000"
    volumes:
      - "./miniodata:/data"
